# Generated by Django 2.1 on 2019-10-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_bookmark_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='description',
            field=models.CharField(blank=True, help_text='simple description text', max_length=50, verbose_name='DESCRIPTION'),
        ),
    ]
